### ISSUE TITLE
Add Speed Control

### ISSUE THREAD

**Issue by vitorjmoriya** [profusion/ios-enhanced-media-player#15]
## Description
Like most modern players, there should be speed control to either increase/decrease the reproduction velocity

## Implementation details
Use the settings menu to set this control

## Potential caveats
N/A

## Acceptance criteria
- [ ] User can toggle between reproduction speed

**Comment by KarenBaliero** [comment]
Additional info:
Speed Control: 0.75 | 1 | 1.25 | 2.
The playback speed list is composed of the following or a subset: 0.25x | 0.5x | 0.75x | Default (1x) | 1.25x | 1.5x | 1.75x | 2x
It can be accessed in the Settings Menu on the Playback Speed entry
The display mode is different from Portrait and Landscape. On Portrait we need to present in a Modal/Drawer
